<?php

namespace AppBundle\Repository;

/**
 * Cartes_jeu_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cartes_jeu_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
