<?php

namespace AppBundle\Repository;

/**
 * Cartes_jeu_cirusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cartes_jeu_cirusRepository extends \Doctrine\ORM\EntityRepository
{
}
