<?php

namespace AppBundle\Repository;

/**
 * Categorie_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
