<?php

namespace AppBundle\Repository;

/**
 * Joueur_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Joueur_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
