<?php

namespace AppBundle\Repository;

/**
 * Modele_carte_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Modele_carte_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
