<?php

namespace AppBundle\Repository;

/**
 * Participant_tournoi_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Participant_tournoi_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
