<?php

namespace AppBundle\Repository;

/**
 * Partie_tournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Partie_tournoiRepository extends \Doctrine\ORM\EntityRepository
{
}
