<?php

namespace AppBundle\Repository;

/**
 * Tounoi_circusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tounoi_circusRepository extends \Doctrine\ORM\EntityRepository
{
}
