app: 
  resource: "@AppBundle/Controller/"
  type: annotation
easy_admin_bundle:
  prefix: /admin
  resource: "@EasyAdminBundle/Controller/"
  type: annotation
fos_user: 
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

