# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

fos_user:
    registration:
        form:
            type: AppBundle\Form\RegistrationType

easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            form:
                fields:

                    - username
                    - email
                    - { property: 'Password', type: 'text', type_options: { required: false } }

                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            show:
                fields:
                    - username
                    - email
                    - roles
                    - password
                    